# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  buildConfiguration: 'Release'

steps:

- task: PowerShell@2
  displayName: 'Set Sauce Labs Environment Variables'
  inputs:
    targetType: filePath
    filePath: ./setSauceEnvironmentVariables.ps1
    arguments: '$env:SAUCE_USERNAME $env:SAUCE_ACCESSKEY'

- task: DotNetCoreCLI@2
  inputs:
    command: test
    projects: '**/*Test/*.csproj'
    arguments: '--configuration $(buildConfiguration)'